# Generated by Django 3.0.5 on 2020-07-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_Class',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
                ('faculty', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('fee', models.IntegerField(max_length=10)),
                ('duration', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Registration',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contactno', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.IntegerField(max_length=20)),
            ],
        ),
    ]
